jenkins:
  systemMessage: "Welcome to Jenya!"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

unclassified:
  location:
    url: "http://localhost:8080/"

jobs:
  - file: /var/jenkins_home/seedJob.groovy
